artifact_location: /Users/jaa1090/Documents/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-Jkaslam/submission/mlflow/0
creation_time: 1694489827446
experiment_id: '0'
last_update_time: 1694489827446
lifecycle_stage: active
name: Default
