artifact_uri: /Users/jaa1090/Documents/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-Jkaslam/submission/mlflow/117368064709046360/38cf8185126341d286768e6b0b85fced/artifacts
end_time: null
entry_point_name: ''
experiment_id: '117368064709046360'
lifecycle_stage: active
run_id: 38cf8185126341d286768e6b0b85fced
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-Red-Single_e23c3_00000
run_uuid: 38cf8185126341d286768e6b0b85fced
source_name: ''
source_type: 4
source_version: ''
start_time: 1694577116895
status: 1
tags: []
user_id: unknown
