artifact_location: /Users/jaa1090/Documents/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-Jkaslam/submission/mlflow/443028157350235937
creation_time: 1694644688862
experiment_id: '443028157350235937'
last_update_time: 1694644688862
lifecycle_stage: active
name: test3
