artifact_location: /Users/jaa1090/Documents/RLClass/week-1-intro-to-deep-rl-and-agent-training-environments-Jkaslam/submission/mlflow/117368064709046360
creation_time: 1694489827456
experiment_id: '117368064709046360'
last_update_time: 1694489827456
lifecycle_stage: active
name: test
